### ISSUE TITLE
Remove Due Date from the Start Your Application Header

### ISSUE THREAD

**Issue by michiQ** [yadaguru/yadaguru-admin#1]
See the screenshot - this is for Katelin or myself to update the language.

Right now the header of the Start your Applciation reminder includes the due date.  It's a little confusing because it says 'Start [Schools] Application 3/1/2017'. That makes it look like we need to start the application on 3/1/2017. However you get to this by clicking on a date by which you have to do this thing (ie the date you have to start the application).   So that dates clear...no need to add the additional date in the header. 

![img_0959](https://cloud.githubusercontent.com/assets/8203279/20216292/c821bb6a-a7e7-11e6-8fe4-9561bd4bc869.jpg)

**Comment by bobderrico80** [comment]
This is most likely an anomaly created by some of the changes planned for the admin interface. V2 will have a slightly different set of variables, that will give us more options for messaging.
